StringsFunctions.ConsideredStrings_Publish() 
# print('*'*300)
# # StringsFunctions.IsDiag()
# StringsFunctions.IsDiag_Publish()
# print('*'*300)
# # StringsFunctions.IsSafeDiag()
# StringsFunctions.IsSafeDiag_Publish()
# print('*'*300)

# # StringsFunctions.IsPred()
# StringsFunctions.IsPred_Publish()
# print('*'*300)

# # StringsFunctions.IsSafeControlByDiag() 
# StringsFunctions.IsSafeControlByDiag_Publish()
# print('*'*300)

# # StringsFunctions.IsSafeControlByProg()
# StringsFunctions.IsSafeControlByProg_Publish()
# print('*'*300)