print('*'*200)
# StringsFunctions.IsDiag()
StringsFunctions.IsDiag_Publish()
print('*'*200)
# StringsFunctions.IsSafeDiag()
StringsFunctions.IsSafeDiag_Publish()
print('*'*200)
# StringsFunctions.IsPred()
StringsFunctions.IsPred_Publish()
print('*'*200)
StringsFunctions.IsSafeControlByDiag() 
StringsFunctions.IsSafeControlByDiag_Publish()
print('*'*200)
# StringsFunctions.IsSafeControlByProg()
StringsFunctions.IsSafeControlByProg_Publish()
print('*'*200)
# StringsFunctions.IsSafeControlByDiagAndProg()
StringsFunctions.IsSafeControlByDiagAndProg_Publish()
print('*'*200)
# StringsFunctions.IsSafeControlByDiagAndProg_SelfPublish()